export const projects = [
  {
    title: "Apple Clone",
    description: "A sleek Apple website clone built with smooth animations and responsive design. Showcases modern UI/UX inspired by Apple's official site.",
    tech: ["React", "TypeScript", "Material-UI", "Tailwind CSS"],
    github: "https://github.com/Raghu-Ng/apple_clone",
    live: "https://appleiclone.netlify.app/",
    image: "/uploads/Appleclone.png",
  },
  {
    title: "Nature's Wheel Pizza",
    description: "A vibrant website for Nature's Wheel Pizza, highlighting delicious menu items with earthy aesthetics. Designed to offer a mouth-watering, eco-friendly brand experience.",
    tech: ["React", "TypeScript", "Tailwind CSS"],
    github: "https://github.com/Raghu-Ng/natureswheel-pizza-with-localStorage-and-polling",
    live: "https://natureswheelpiizza.netlify.app/",
    image: "/uploads/pizza.png",
  },
  {
    title: "Aura Media Production",
    description: "A dynamic production studio specializing in high‑impact videography and post‑production workflows—from ideation to final edit. The site highlights their collaborative approach, rich service offerings, and visually engaging process.",
    tech: ["HTML", "CSS", "JavaScript"],
    github: "https://github.com/Raghu-Ng/natureswheel-pizza-with-localStorage-and-polling",
    live: "https://theauraproductions.rf.gd/?i=1",
    image: "/uploads/aura.png",
  },
  {
    title: "QuizQuest",
    description: "An interactive quiz platform that challenges users across diverse topics, showcasing the power of modern web technologies and AI integration.",
    tech: ["React", "AI Integration"],
    github: "https://github.com/Raghu-Ng/Quiz",
    live: "https://quizzzzzzzzzzzzzzzzzz.netlify.app/",
    image: "/uploads/quiz.png",
  },
  {
    title: "NewsStream",
    description: "A Streamlit-based news aggregator that fetches and summarizes the latest headlines using RSS feeds and simple NLP techniques.",
    tech: ["Python", "Streamlit", "NLTK", "newspaper3k", "BeautifulSoup"],
    github: "https://github.com/Raghu-Ng/News",
    live: "https://newsss.streamlit.app/",
    image: "/uploads/news.png",
  },
  {
    title: "BookRealm",
    description: "A sleek and user-friendly platform for book lovers to explore, review, and keep track of their reading journey. Built with modern web practices to offer smooth browsing and interactive features.",
    tech: ["React", "TypeScript", "Tailwind CSS"],
    github: "https://github.com/Raghu-Ng/BookRealm",
    live: "https://bookrealmbb.netlify.app/",
    image: "/uploads/bookrealm.png",
  }, 
  {
    title: "Draw Canvas App",
    description: "A minimalist web drawing canvas allowing users to sketch, choose colors, and erase in a clean, intuitive environment.",
    tech: ["React", "JavaScript", "HTML5 Canvas"],
    github: "https://github.com/Raghu-Ng/draw-canvas",
    live: "https://draw-canvas-coral.vercel.app/",
    image: "/uploads/drawcanvas.png",
  },
  {
    title: "Hotels Near Me",
    description: "A React-powered hotel search tool that helps users discover nearby hotels using geolocation, browse details, and explore availability in a clean, intuitive interface.",
    tech: ["React", "JavaScript", "CSS", "Geolocation API"],
    github: "https://github.com/Raghu-Ng/HotelsNearMe",
    live: "https://hotelsnearme.netlify.app/",
    image: "/uploads/hotelsnearme.png",
  },
  {
    title: "Chat with the PDFs",
    description: "A Streamlit-powered app that lets users upload PDF documents and interactively chat with their content using RAG (Retrieval-Augmented Generation) via LangChain, FAISS, and an LLM.",
    tech: ["Python", "Streamlit", "LangChain", "FAISS", "OpenAI/LLM"],
    github: "https://github.com/Raghu-Ng/Chat-with-the-pdfs",
    live: "https://chat-with-the-pdfs-bwbaut4vgdimlq7g48n8rc.streamlit.app/",
    image: "/uploads/chatwithpdfs.png",
  },
    
];
